# DEVELOPMENT DOCKER-COMPOSE FILE
version: "2"

services:

  http_server:
    image: nginx:1.13.3-alpine
    restart: always
    ports:
     - "80:80"
    volumes:
     - ./www/wp_files/:/www:ro
     - ./configs/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
     - ./configs/nginx/conf.d:/etc/nginx/conf.d:ro
    links:
     - wp_server

  wp_server:
    build:
      context: ./docker-images/php/
      args:
        PHP_VERSION: 7.1
        # PHP_VERSION: 7.0
        # PHP_VERSION: 5.6
    user: ${UID}:www-data
    volumes:
     - ./www/wp_files/:/www
     - ./configs/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    links:
     - mariadb

  mariadb:
    image: mariadb
    restart: always
    ports:
     - "127.0.0.1:3306:3306"
    volumes:
     - ./www/wp_DB:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=${DB_PASS}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
     - PMA_HOST=mariadb
    links:
     - mariadb
    ports:
     - "8888:80"

  wordmove:
    build:
      context: ./docker-images/wordmove/
    command: 'echo "Hello From Wordmove"'
    volumes:
     - ./www/wp_files/:/www
     # Movefile
     - ./configs/wordmove/:/home/
     # For ssh
     - ${HOME}/.ssh/:/root/.ssh:ro
     - /etc/passwd:/etc/passwd:ro
    links:
     - mariadb