version: "2"

services:

  wp_http_server:
    image: nginx:1.13.3-alpine
    container_name: wp_http_server
    restart: always
    ports:
     - "80:80"
     - 443:443
    volumes:
     - ./www/wp_files/:/www:ro
     - ./configs/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
     - ./configs/nginx/conf.d:/etc/nginx/conf.d:ro

    links:
     - wp_server

  wp_server:
    build:
      context: ./docker-images/php/
      args:
        PHP_VERSION: 7.1
        # PHP_VERSION: 7.0
        # PHP_VERSION: 5.6
    user: ${UID}:www-data
    container_name: wp_server
    volumes:
      - ./www/wp_files/:/www
      - ./configs/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    links:
     - wp_mariadb

  wp_mariadb:
    image: mariadb
    container_name: wp_mariadb
    restart: always
    volumes:
     - ./www/wp_DB:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=YOUR_SUPER_SECURE_PASSWORD

  wp_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_phpmyadmin
    restart: always
    environment:
     - PMA_HOST=wp_mariadb
    links:
     - wp_mariadb
    ports:
     - "8888:80"