version: "2"

services:

  wp_http_server:
    image: nginx:1.13.3-alpine
    container_name: wp_http_server
    ports:
     - "80:80"
    volumes:
     - ./www/wp_files/:/www:ro
     - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
     - wp_server

  wp_server:
    # image: dianjuar/wordpress:php7.1-fpm-alphine_wp-cli1.3.0
    build: ./docker-images/php/
    container_name: wp_server
    volumes:
      - ./www/wp_files/:/www
      # - ./php/:/usr/local/etc/php/conf.d/
    links:
     - wp_mariadb

  wp_mariadb:
    image: mariadb
    container_name: wp_mariadb
    restart: always
    volumes:
     - ./www/wp_DB:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=YOUR_SUPER_SECURE_PASSWORD

  wp_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_phpmyadmin
    restart: always
    environment:
     - PMA_HOST=wp_mariadb
    links:
     - wp_mariadb
    ports:
     - "8888:80"